### ISSUE TITLE
Move wireframe CSS from Lark

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-theme-wireframe#1]
A follow-up of https://github.com/ckeditor/ckeditor5-theme-lark/issues/67.

**Comment by pjasiun** [comment]
Didn't we agree to put it in `ckeditor5-ui`?

**Comment by oleq** [comment]
No, I guess not. AFAIR we decided to keep it as a separate theme. But anyway, if we decide to move it to `ckeditor5-ui`, that's not a problem. The problem is to extract the right CSS, which is quite hard. I took me a long time to do it and I wasn't sure in many places.

**Comment by oleq** [comment]
Eventually, it turned out that keeping wireframe theme in ckeditor5-ui is cleaner. Moving to https://github.com/ckeditor/ckeditor5-ui/issues/136.
